---
- name: install php packages
  apt: pkg={{ item }} state=present
  with_items:
      - php7.0
      - php7.0-cgi
      - php7.0-cli
      - php7.0-common
      - php7.0-curl
      - php7.0-json
      - php7.0-ldap
      - php7.0-mysql
      - php7.0-opcache
      - php7.0-readline
      - php7.0-xml
      - php7.0-xmlrpc
      - php7.0-bcmath
      - php7.0-bz2
      - php7.0-fpm
      - php7.0-mbstring
      - php7.0-mcrypt
      - php7.0-soap
      - php7.0-zip

