---
- name: apt-get update before installing
  apt: update_cache=yes

  # upgrade する前にインストールする必要あり
- name: install aptitude
  apt: pkg=aptitude

- name: apt-get upgrade before installing
  apt: upgrade=full
  become: yes

- name: install essential packages
  apt: pkg={{ item }} state=present
  with_items:
      - curl
      - wget
      - nkf
      - zsh
      - vim
      - tmux
  
- name: install git
  apt: pkg=git-core state=present

- name: change default shell to zsh
  shell: chsh -s $(which zsh)
