---
- name: apt-get update before installing
  apt: update_cache=yes

  # upgrade する前にインストールする必要あり
- name: install aptitude
  apt: pkg=aptitude

- name: apt-get upgrade before installing
  apt: upgrade=full
  become: yes

- name: install essential packages
  apt: pkg={{ item }} state=present
  with_items:
      - curl
      - wget
      - nkf
      - zsh
      - vim
      - tmux
      - build-essential # http://qiita.com/TsutomuNakamura/items/7a8362efefde6bc3c68b#ppa-%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%A6%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%99%E3%82%8B
      - language-pack-ja-base # ssh するときに言語環境でエラーでるので対処
  
- name: install git
  apt: pkg=git-core state=present

- name: change default shell to zsh
  shell: chsh -s $(which zsh)
  become: yes

- name: install lua to vim
  shell: aptitude install vim-gnome
  become: yes
