---

-   
    name: Install some software for development
    hosts: vagrants
    user: vagrant
    sudo: yes

    roles:
        - system
        - nginx
        - mysql
        - dotfiles
        - composer
        - anyenv
