---
-   
    name: Install some software for development
    hosts: vagrants
    user: vagrant
    become: yes

    roles:
        - system
        - nginx
        - mysql
        - dotfiles
        - anyenv
