---

-   
    name: Install some software for development
    hosts: vagrants
    user: vagrant
    sudo: yes

    roles:
        - system
        - nginx
        - mysql
        - java
        - php
        - golang
        - nodejs
        - tmux
        - zsh
        - vim
        - git
        - dotfiles
